server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
        - id : member
          uri: http://127.0.0.1:8001
          predicates:
            - Path=/member/**  # 断言，路径相匹配的进行路由

      globalcors:

        cors-configurations:
          '[/**]':
            # 是否允许携带cookie
            allowCredentials: true
            # 允许携带的头信息
            allowedHeaders: '*'
            # 允许的请求方式
            allowedMethods: '*'
            # 允许请求来源（老版本叫allowedOrigin）
            allowedOriginPatterns: '*'
            # 跨域检测的有效期，会发起一个OPTION请求
            maxAge: 3600
            ####vuex配合h5 session缓存，解决浏览器刷新丢失数据的问题